name: CD

on:
  pull_request:
    paths-ignore:
      - 'docs/**'

# MVD runs using docker-compose based setup with no dependency on cloud services.

jobs:

  VerifyLocalTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/gradle-setup

      # Use EDC FileSystem vault for CI run.
      - name: 'Build launcher'
        run: ./gradlew -DuseFsVault="true" :launcher:shadowJar

      # Build Registration Service runtime JAR locally.
      # The result is a JAR file in launcher/build/libs.
      - name: 'Build Registration Service launcher'
        run: ./gradlew :launcher:shadowJar
        working-directory: ${{ runner.temp }}/RegistrationService

      - name: 'Copy Registration Service CLI'
        run: |
          mvn dependency:copy -Dartifact=org.eclipse.dataspaceconnector.registrationservice:registration-service-cli:$REGISTRATION_SERVICE_VERSION:jar:all -DoutputDirectory=.
          mv registration-service-cli-$REGISTRATION_SERVICE_VERSION-all.jar registration-service-cli.jar
        working-directory: system-tests/resources/cli-tools
        env:
           REGISTRATION_SERVICE_VERSION: 0.0.1-SNAPSHOT

      - name: 'Copy Identity Hub CLI'
        run: |
          mvn dependency:copy -Dartifact=org.eclipse.dataspaceconnector.identityhub:identity-hub-cli:$IDENTITY_HUB_VERSION:jar:all -DoutputDirectory=.
          mv identity-hub-cli-$IDENTITY_HUB_VERSION-all.jar identity-hub-cli.jar
        working-directory: system-tests/resources/cli-tools
        env:
          IDENTITY_HUB_VERSION: 0.0.1-SNAPSHOT

      - name: 'Upgrade docker-compose (for --wait option)'
        run: |
          sudo curl -L https://github.com/docker/compose/releases/download/v2.6.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: 'Run MVD docker-compose'
        run: docker-compose -f system-tests/docker-compose.yml up --build --wait
        timeout-minutes: 10
        env:
          REGISTRATION_SERVICE_LAUNCHER_PATH: ${{ runner.temp }}/RegistrationService/launcher

      - name: 'Unit and system tests'
        run: ./gradlew test
        timeout-minutes: 10
        env:
          TEST_ENVIRONMENT: "local"

      - name: 'docker-compose logs'
        run: docker-compose -f system-tests/docker-compose.yml logs
        if: always()
        env:
          REGISTRATION_SERVICE_LAUNCHER_PATH: ${{ runner.temp }}/RegistrationService/launcher
